### ISSUE TITLE
Any chance to bump PHP req to 8.* speedily?

### ISSUE THREAD

**Issue by rulatir** [phpDocumentor/FlyFinder#38]
As per topic, can we extend the PHP requirement to 8.*?

**Comment by jaapio** [comment]
If you are able to provide a PR things can go quite fast. But right now I do not have time to check this myself. 

So feel free to open a PR to enable testing on php8 and stretch the PHP requirement in `composer.json`

**Comment by jnkowa-gfk** [comment]
@jaapio PR provided: #39

**Comment by arthurduarte1** [comment]
Will be great if @jnkowa-gfk pull request could be accepted.
